AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys OpenComply Platform to AWS Organization, targeting only Organizational Units (OUs)

Parameters:
  IAMUsernameInOrganizationAccount:
    Type: String
    Default: OpenComplyIAMUser
    Description: IAM User to create

  RoleNameInAccount:
    Type: String
    Default: OpenComplyReadOnly
    Description: The name of the role that will be assumed in each member account.

  OrganizationUnitList:
    Type: CommaDelimitedList
    Description: >
      List of Organizational Unit (OU) IDs to deploy the stackset to.
      Enter each OU ID without spaces.

Conditions:
  HasOUs: !Not [ !Equals [ !Join ["", !Ref OrganizationUnitList ], "" ] ]

Resources:
  # IAM Role in the Management Account
  OrganizationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref RoleNameInAccount
      Description: Allows the OpenComply platform to gather inventory of the organization and member accounts
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub '${AWS::AccountId}'
            Action:
              - 'sts:AssumeRole'
              - 'sts:TagSession'
      Policies:
        - PolicyName: OpenComplyRoleAssumption
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'organizations:List*'
                  - 'sts:AssumeRole'
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSSSODirectoryReadOnly
        - arn:aws:iam::aws:policy/AWSSSOReadOnly
        - arn:aws:iam::aws:policy/IAMAccessAdvisorReadOnly
        - arn:aws:iam::aws:policy/IAMAccessAnalyzerReadOnlyAccess

  # IAM User in the Management Account
  IAMUserInOrganizationAccount:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: !Ref IAMUsernameInOrganizationAccount
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
        - arn:aws:iam::aws:policy/SecurityAudit
        - arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess
        - arn:aws:iam::aws:policy/IAMAccessAnalyzerReadOnlyAccess
        - arn:aws:iam::aws:policy/IAMAccessAdvisorReadOnly
      Policies:
        - PolicyName: OpenComplySSOPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'sso:Describe*'
                  - 'sso:Get*'
                  - 'sso:List*'
                  - 'sso:Search*'
                  - 'sso-directory:DescribeDirectory'
                Resource: '*'
        - PolicyName: OpenComplyAssumeRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'sts:AssumeRole'
                Resource: !Sub 'arn:aws:iam::*:role/${RoleNameInAccount}'

  # StackSet to Deploy Roles to Member Accounts (Organizational Units Only)
  MemberAccountRoleStackSet:
    Type: 'AWS::CloudFormation::StackSet'
    Properties:
      StackSetName: OpenComplyMemberAccountRollout
      Description: Stack Set that will roll out to member accounts within specified Organizational Units
      Capabilities:
        - CAPABILITY_NAMED_IAM
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      PermissionModel: SERVICE_MANAGED
      ManagedExecution:
        Active: true
      StackInstancesGroup:
        - DeploymentTargets: 
            OrganizationalUnitIds: !Ref OrganizationUnitList
          Regions: 
            - !Ref AWS::Region
          OperationPreferences:
            MaxConcurrentCount: 50            # Deploy to 50 accounts at a time
            FailureTolerancePercentage: 10    # Tolerate failures in up to 10% of accounts per batch
      Parameters: 
        - ParameterKey: OrganizationIAMUserArn
          ParameterValue: !Sub "arn:aws:iam::${AWS::AccountId}:user/${IAMUsernameInOrganizationAccount}"
        - ParameterKey: MemberAccountRoleName
          ParameterValue: !Ref RoleNameInAccount
      TemplateBody: |
        {
          "AWSTemplateFormatVersion": "2010-09-09",
          "Description": "Create a reader role in member accounts.",
          "Parameters": {
              "OrganizationIAMUserArn": {
                  "Type": "String",
                  "Description": "The IAM User ARN that is allowed to assume the role."
              },
              "MemberAccountRoleName": {
                  "Type": "String",
                  "Description": "The name of the role that will be deployed in each member account."
              }
          },
          "Resources": {
              "OpenComply": {
                  "Type": "AWS::IAM::ManagedPolicy",
                  "Properties": {
                      "ManagedPolicyName": "OpenComplyPolicy",
                      "Description": "A Limited policy to allow cloudquery to do its job",
                      "PolicyDocument": {
                          "Version": "2012-10-17",
                          "Statement": [
                              {
                                  "Effect": "Deny",
                                  "Resource": "*",
                                  "Action": [
                                      "cloudformation:GetTemplate",
                                      "dynamodb:GetItem",
                                      "dynamodb:BatchGetItem",
                                      "dynamodb:Query",
                                      "dynamodb:Scan",
                                      "ec2:GetConsoleOutput",
                                      "ec2:GetConsoleScreenshot",
                                      "ecr:BatchGetImage",
                                      "ecr:GetAuthorizationToken",
                                      "ecr:GetDownloadUrlForLayer",
                                      "kinesis:Get*",
                                      "lambda:GetFunction",
                                      "logs:GetLogEvents",
                                      "s3:GetObject",
                                      "sdb:Select*",
                                      "sqs:ReceiveMessage"
                                  ]
                              }
                          ]
                      }
                  }
              },
              "MemberAccountReadOnlyRole": {
                  "Type": "AWS::IAM::Role",
                  "Properties": {
                      "RoleName": { "Ref" : "MemberAccountRoleName" },
                      "Description": "Read Only Access to fetch inventory from member accounts",
                      "ManagedPolicyArns": [
                          {
                              "Ref": "OpenComply"
                          },
                          "arn:aws:iam::aws:policy/ReadOnlyAccess",
                          "arn:aws:iam::aws:policy/SecurityAudit",
                          "arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess",
                          "arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess",
                          "arn:aws:iam::aws:policy/IAMAccessAnalyzerReadOnlyAccess",
                          "arn:aws:iam::aws:policy/IAMAccessAdvisorReadOnly"
                      ],
                      "MaxSessionDuration": 28800,
                      "AssumeRolePolicyDocument": {
                          "Version": "2012-10-17",
                          "Statement": [
                              {
                                  "Effect": "Allow",
                                  "Principal": {
                                      "AWS": {
                                          "Fn::Sub": "${OrganizationIAMUserArn}"
                                      }
                                  },
                                  "Action": [
                                      "sts:AssumeRole",
                                      "sts:TagSession"
                                  ]
                              }
                          ]
                      }
                  }
              }
          }
        }

Outputs:
  IAMUserNameInMasterAccount:
    Description: IAM Username in the Master Account.
    Value: !Ref IAMUsernameInOrganizationAccount

  IAMRoleName:
    Description: IAM Rolename that is created.
    Value: !Ref RoleNameInAccount
